language: ruby
sudo: required
dist: trusty
services:
- docker
rvm:
- 2.4.2
before_install:
install:
before_script:
script:
- make help
deploy:
  provider: script
  script: ci/deploy.sh
  on:
    branch: master
notifications:
  email:
    recipients:
    - brandon@atscale.run
    on_success: change
    on_failure: change
